CREATE TABLE `list_aktivitas_mahasiswa` (
  `nm_asaldata` varchar(255) DEFAULT NULL,
  `asal_data` varchar(255) DEFAULT NULL,
  `id_aktivitas` varchar(100) NOT NULL,
  `program_mbkm` int(11) DEFAULT NULL,
  `nama_program_mbkm` varchar(225) DEFAULT NULL,
  `jenis_anggota` int(11) DEFAULT NULL,
  `nama_jenis_anggota` varchar(255) DEFAULT NULL,
  `id_jenis_aktivitas` char(32) DEFAULT NULL,
  `nama_jenis_aktivitas` varchar(50) NULL DEFAULT '',
  `id_prodi` varchar(100) DEFAULT NULL,
  `nama_prodi` varchar(30) NULL DEFAULT '',
  `id_semester` smallint(5) UNSIGNED ZEROFILL DEFAULT NULL,
  `nama_semester` text DEFAULT NULL,
  `judul` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `keterangan` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lokasi` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sk_tugas` tinyint(1) DEFAULT 0,
  `sumber_data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_sk_tugas` datetime DEFAULT NULL,
  `tanggal_mulai` date DEFAULT NULL,
  `tanggal_selesai` date DEFAULT NULL,
  `untuk_kampus_merdeka` tinyint(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;