<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Oops, Something Went Wrong!</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #2c3e50;
            color: #ecf0f1;
            text-align: center;
            padding: 50px;
        }
        h1 {
            font-size: 3em;
            margin-top: 20px;
        }
        .error-message {
            font-size: 1.5em;
            margin: 30px 0;
        }
        .imposter {
            width: 200px;
            height: auto;
            margin-top: 30px;
        }
        .retry-button {
            background-color: #e74c3c;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 1em;
            transition: background-color 0.3s ease;
        }
        .retry-button:hover {
            background-color: #c0392b;
        }

        .rotate-scale-up {
            -webkit-animation: rotate-scale-up 1s linear infinite both;
            animation: rotate-scale-up 1s linear infinite both;
        }

        /* ----------------------------------------------
 * Generated by Animista on 2024-12-17 15:25:28
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

        /**
         * ----------------------------------------
         * animation rotate-scale-up
         * ----------------------------------------
         */
        @-webkit-keyframes rotate-scale-up {
            0% {
                -webkit-transform: scale(1) rotateZ(0);
                transform: scale(1) rotateZ(0);
            }
            50% {
                -webkit-transform: scale(2) rotateZ(180deg);
                transform: scale(2) rotateZ(180deg);
            }
            100% {
                -webkit-transform: scale(1) rotateZ(360deg);
                transform: scale(1) rotateZ(360deg);
            }
        }
        @keyframes rotate-scale-up {
            0% {
                -webkit-transform: scale(1) rotateZ(0);
                transform: scale(1) rotateZ(0);
            }
            50% {
                -webkit-transform: scale(2) rotateZ(180deg);
                transform: scale(2) rotateZ(180deg);
            }
            100% {
                -webkit-transform: scale(1) rotateZ(360deg);
                transform: scale(1) rotateZ(360deg);
            }
        }


        /*#play-button {*/
        /*    display: none;*/
        /*}*/
    </style>
</head>
<body>

<h1>Whoops! Something Went Wrong...</h1>
<div class="error-message">
    <p>Looks like an impostor has sabotaged the system! 🚨</p>
    <p>We are working to fix it, please try again later. Or report the impostor!</p>
</div>
<div>
    <h1> MY IMPOSTOR !!!!!! </h1>
    <h1 id="impostor" class="rotate-scale-up"  style="color : red;display:none;"> <?= $_SERVER['impostor'] ?> </h1>
    <h3 id="file" style="color : orange;display:none;"><?= $_SERVER['file'] ?></h3>
</div>
<img src="https://img.icons8.com/?size=100&id=1dkd0sl4w1aa&format=png&color=000000" alt="Impostor" class="imposter">


<!-- Ambulance Sound (will be triggered by button click) -->
<audio id="ambulance-sound">
    <source src="<?= base_url('/sound/impostor.mp3') ?>" type="audio/mp3">
</audio>


<!-- Play Button to Start Sound -->
<div>
    <button id="play-button" class="retry-button" onclick="impostor()">CEK IMPOSTOR</button>
</div>

<script>
function impostor() {
    document.getElementById('ambulance-sound').play();
    var impostor = document.getElementById('impostor');
    var file     = document.getElementById('file');

    if (impostor.style.display === 'none' || impostor.style.display === '') {
        impostor.style.display = 'block';
        file.style.display     = 'block';
    }
}
</script>
</body>
</html>
